language: python
python:
  - '3.5'
  - '3.8'
script:
  - coverage run -m unittest tests
after_success:
  - codecov
deploy:
  provider: pypi
  user: __token__
  password:
    secure: c+5GnESd5mSirF5mq+3MSeiIcvfAcyT/Zjt4/dFJe2O/5Z6l6H5pZAIvVFBmrizK61/Y/uwcHiwpkep6InLlqgWxnJKvxT7m/OkrNwtttTKMtc9trRX9mzBXo9jBVDJwWr/kX/0K1PWp/0MBuv1qYXrRY+V3q5QsX9pnFlQuhVEnRSYaQW9e8lLUIt11sMySNFetzi/PbQIjY7q0swMjvajFCt2BlaSG6ZVdbHR2ewv2O2tWcAVBhIBFzocgK+T//FBpg6ycQjTWla882WledLy8lWjUfNEho0vQmseqYf8P7TgK9y5oFRXMOpc0yxVFohYSRWvn7WPU2FZdKIcdVCzBtmTVb+/w7xtp5X8jWaS4xxaha0X9fGjsnlZoB0rdPsscbh/BrP3NyPyNkF2I8a8bMwFs9+CxZC4+qy6qZkGXLJzjXWGF6N6A8v4LcEcJ9CuXYYdnOHst5FFlyPZO/kSnDro5z1aF9mya4jdRjMGLaSytTHtNkFCHKhL7BjmkJX3k6RAJzhSmafZ+y/SQsKM47OjcK4dJ3DGy73w6/o/Mok+GMOdlWuoljP2/jhWHHNg3giv+zz2pXjcQLoaQRpCpMOAq8hpTzHwfXzw97mgbYQlFXCI5NFfZwHW0yc893M/XSuDOSi+SK8DB+EK6bENMElfdNTNV2hQS4V34x0Q=
  distributions: sdist bdist_wheel
  skip_existing: true
  skip_cleanup: true
  on:
    tags: true
